export { default as NotFound } from "./NotFound";
export { default as Home } from "./Home";
export { default as Dashboard } from "./Dashboard";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as AdminNotFound } from "./AdminNotFound";
export { default as Tours } from "./Tours";
export { default as Tour } from "./Tour";
export { default as Booking } from "./Booking";